# Generated by Django 5.2.17 on 2026-09-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tron_payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incomingpayment',
            new_name='django_tron_network_e5788f_idx',
            old_name='django_tron_network_5efdd7_idx',
        ),
        migrations.RenameIndex(
            model_name='incomingpayment',
            new_name='django_tron_wallet__e19c45_idx',
            old_name='django_tron_wallet__7eeb74_idx',
        ),
        migrations.RenameIndex(
            model_name='managedwallet',
            new_name='django_tron_network_a4ee9e_idx',
            old_name='django_tron_network_9b44f1_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurysweep',
            new_name='django_tron_network_e15999_idx',
            old_name='django_tron_network_67fc89_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurysweep',
            new_name='django_tron_wallet__51ab86_idx',
            old_name='django_tron_wallet__1b6504_idx',
        ),
    ]
