[tox]
env_list = py312, py313
isolated_build = true

[testenv]
package = wheel
extras = test
commands =
    pytest

[testenv:lint]
extras = test
commands =
    ruff check src tests
    ruff format --check src tests
